trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: Bash@3
  inputs:
    targetType: inline
    script: |
      # The reason this has to be done - https://github.com/NuGet/Home/issues/8022
      # rename npm package reference in adal-node
      # covers package.json and any file referencing package
      find ./node_modules/adal-node -type f -exec sed -i -e 's/xpath.js/xpathjs/g' {} \;

      # rename the xpath.js npm package folder and name
      mv ./node_modules/xpath.js ./node_modules/xpathjs
      
      # change the name in the package.json to reflect naming change
      find ./node_modules/xpathjs -type f -exec sed -i -e 's/xpath.js/xpathjs/g' {} \;
  displayName: 'fixup for NuGet Pack Issue'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    nobuild: true
    packDirectory: '$(Build.ArtifactStagingDirectory)'